### ISSUE TITLE
Maintainer request

### ISSUE THREAD

**Issue by jmfederico** [jgosmann/pylint-venv#1]
Hi @jgosmann 

I am interested in continuing developing this module and keeping it up to date with new venv in Python3.

Would you consider giving me permission to maintain the package in Pypi?

https://pypi.org/user/jmfederico/

Thanks

**Comment by jgosmann** [comment]
I'm happy to accept pull requests and do the PyPI releases myself for now. But I am not comfortable giving maintainer permissions to someone I haven't interacted at all with so far.

**Comment by jmfederico** [comment]
That sounds reasonable.

Will make a PR.
