### ISSUE TITLE
Pylintrc init-hook documentation update needed

### ISSUE THREAD

**Issue by PenelopeFudd** [jgosmann/pylint-venv#5]
Hi;

Getting the system-installed pylint to import modules in my virtualenv-based project has been a pain; glad I found this module!

That said, it wasn't drop-dead easy for me to configure pylint correctly to use it!  :-(

Environment: MacOS Catalina (10.15.5), Brew, python 3.8.3, pylint 2.5.3, asteroid 2.4.2

The instructions at https://pypi.org/project/pylint-venv/ said to add this to ~/.pylintrc:
```
init-hook=
    try: import pylint_venv
    except ImportError: pass
    else: pylint_venv.inithook()
```

This didn't seem to have any effect, so after much mucking about I came up with this:
```
init-hook=
    import sys
    sys.path.append("/usr/local/lib/python3.8/site-packages")
    import pylint_venv
    pylint_venv.inithook(force_venv_activation=True)
```
I'm still not happy with my efforts, since who puts python version numbers in their code?  I mean, really?  :-)

If you could change the documentation a bit to make it easier for the next folks, that'd be great!

Thanks

**Comment by jgosmann** [comment]
I think to change the documentation in a helpful way, I first need to understand what exactly is causing the issue for you.

Do you need to add both the `sys.path.append` line and the `force_venv_activation` flag? The latter indicates to me that your pylint itself is running in a virtual environment. What is the output of `which -a pylint`? The former might be an indication that this virtual environment was created without access to system site packages. Assuming that this is correct, I would like to understand, why that pylint is running in a virtual environment and where this environment comes from.

(Personally, I am using MacPorts where the state instructions work. But Homebrew might have a different behaviour.)

**Comment by PenelopeFudd** [comment]
Here is my test setup:
```
$ brew install pylint
$ mkdir /tmp/foo
$ cd /tmp/foo
$ virtualenv -p $(which python3) python
$ source python/bin/activate
$ pip install --upgrade pip
$ pip install requests

$ cat <<'EOF' > test.py
import requests
print("Hello world!")
EOF

$ pylint test.py

************* Module test
test.py:1:0: C0114: Missing module docstring (missing-module-docstring)
test.py:1:0: E0401: Unable to import 'requests' (import-error)
test.py:1:0: W0611: Unused import requests (unused-import)

----------------------------------------------------------------------
Your code has been rated at -25.00/10 (previous run: -25.00/10, +0.00)
```
Then I add the following to ~/.pylintrc:
```
init-hook=
    import sys; sys.path.append("/usr/local/lib/python3.8/site-packages")
    try: import pylint_venv; pylint_venv.inithook(force_venv_activation=True)
```
Retesting gives:
```
$ pylint test.py

Using env: /private/tmp/foo/python
************* Module test
test.py:1:0: C0114: Missing module docstring (missing-module-docstring)
test.py:1:0: W0611: Unused import requests (unused-import)

------------------------------------------------------------------
Your code has been rated at 0.00/10 (previous run: 0.00/10, +0.00)
```

* `which -a pylint` gives `/usr/local/bin/pylint`.
* If I take out the sys.path.append, then `import pylint_venv` fails.  
* If I take out the `force_venv_activation` then pylint says `Unable to import 'requests'`.

The default sys.path contains:
```
'/private/tmp/foo',
'/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python38.zip',
'/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8',
'/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload',
'/usr/local/lib/python3.8/site-packages',
'/usr/local/Cellar/protobuf/3.12.3_1/libexec/lib/python3.8/site-packages'
```
The virtualenv sys.path contains: 
```
'/private/tmp/foo', 
'/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python38.zip', 
'/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8', 
'/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/lib-dynload', 
'/private/tmp/foo/python/lib/python3.8/site-packages' 
```
(BTW: I recently started putting the virtualenv in a directory called 'python' because it radically simplifies creating AWS Lambda layers.)

```
$ brew info pylint

pylint: stable 2.5.3 (bottled)
It's not just a linter that annoys you!
https://github.com/PyCQA/pylint
/usr/local/Cellar/pylint/2.5.3 (1,022 files, 11MB) *
  Poured from bottle on 2020-07-10 at 16:32:24
From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/pylint.rb
License: GPL-2.0
==> Dependencies
Required: python@3.8 ✔
==> Analytics
install: 727 (30 days), 2,660 (90 days), 7,981 (365 days)
install-on-request: 727 (30 days), 2,654 (90 days), 7,977 (365 days)
build-error: 0 (30 days)
```

I don't know how pylint-venv determines when to do venv activation, but it seems to be missing this case, so force is needed.  :-/

**Comment by jgosmann** [comment]
There is one more piece of information I could use. According to the logs above you created the virtualenv with `virtualenv -p $(which python3) python`. What is the output of `which -a python3`?

**Comment by PenelopeFudd** [comment]
Here:
```
$ for n in $(which -a python3); do echo === $n $($n -V); done

=== /usr/local/bin/python3 Python 3.8.5
=== /usr/bin/python3 Python 3.8.2
```

**Comment by jgosmann** [comment]
Thank you, I do understand the interplay of the different Python environments now. Please take a look at #9.

**Comment by jgosmann** [comment]
I assume this has been resolved with the added troubleshooting documentation and the commit [a8d0dd4](https://github.com/jgosmann/pylint-venv/commit/a8d0dd4172d0449cec7fecba3433d34c50ad9872).
