### ISSUE TITLE
How to configure pylint-venv in VS Code?

### ISSUE THREAD

**Issue by Sayam753** [jgosmann/pylint-venv#7]
Hello developers
Thanks for this excellent library. `pylint-venv` works all good in command line. I was wondering if there is a way to configure this in VS Code as well.

I have configuring VSCode user settings using `pylintArgs` something like this but this does not seem to work.
```json
"python.linting.pylintArgs": [
    "--init-hook=import pylint_venv; pylint_venv.inithook()",
],
```
and 
```json
"python.linting.pylintArgs": [
    "--init-hook",
    "import pylint_venv; pylint_venv.inithook()",
],
```
Any help on this? Thanks

EDIT: Just open VSCode in `virtualenv` itself. No need to configure anything. And `pylint-venv` works like a charm.

**Comment by Sayam753** [comment]
Looking upon possible solutions inspired from #5 , I am able to configure VS Code by -
```json
"python.linting.pylintArgs": [
        "--init-hook",
        "import sys;sys.path.append('/Users/user/Env/only_aws/lib/python3.7/site-packages');import pylint_venv;pylint_venv.inithook(force_venv_activation=True)"
    ]
```
I am closing this issue. But also, I would love to know if this behaviour from `pylint-venv` is expected or not.
Thanks

**Comment by Sayam753** [comment]
Figuring out solutions involving use of `.pylintrc`, this [comment](https://github.com/Microsoft/vscode-python/issues/442#issuecomment-389840215) has been super useful. 
I just thought it can be helpful for anyone figuring out how to configure this library with `.pylintrc`. Thanks!

**Comment by jgosmann** [comment]
You might want to take a look at #9. That might clarify a bit what is going on here? Seem like you pylint is also installed in a virtual environment (thus requiring the `force_venv_activation` flag) that is separate from the environment in which pylint-venv is installed (requiring the `sys.path` modification).

**Comment by Sayam753** [comment]
Hi @jgosmann 
Thanks for the reply. Both `pylint` and `pylint-venv` are installed in the same environment (system-site-packages). I am able to run `pylint` through terminal with `init-hook` all set and `virtualenv` activated.
I played around more with VSCode and `pylint-venv`. Removing the import of `pylint-venv` from `.vscode/settings.json` also worked the same.

```json
"python.linting.pylintArgs": [
        "--init-hook",
        "import sys; sys.path.append('/Users/user/Env/only_aws/lib/python3.7/site-packages')"
    ]
```
Now, from this observation, I can say that `VSCode` does not activate the environment before running `pylint` and thus, `init-hook` configured in `.pylintrc` is not able to detect the environment.
So, we only need to append the path of `virtualenv` packages. But I am not 100% sure about this behaviour of VSCode.

**Comment by Sayam753** [comment]
This is getting really interesting. 
* If I open VSCode in base env (where `pylint` and `pylint-venv` are installed) and then select a new `virtualenv`, we need to pass a path to `pylintArgs`.
```json
"python.linting.pylintArgs": [
        "--init-hook",
        "import sys; sys.path.append('/Users/user/Env/only_aws/lib/python3.7/site-packages')"
    ]
```
* And if I open VSCode in `virtualenv` itself, I do not need to configure anything at all. And `pylint-venv` works like a charm.

I edited my initial message as well to open VSCode in virtualenv.
Thanks
Sayam
